export const QURAN_SURAH_LIST = [
  {
    number: 1,
    name: 'Al-Fatiha',
    arabicName: 'الفاتحة',
    revelationPlace: 'Meccan',
    versesCount: 7,
    meaning: 'The Opening',
    description: 'Recited in every unit of prayer, this chapter is a comprehensive supplication.',
    verses: [
      {
        number: 1,
        arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
        transliteration: 'Bismillāhir-Raḥmānir-Raḥīm',
        translation: 'In the Name of Allah—the Most Compassionate, Most Merciful.',
      },
      {
        number: 2,
        arabic: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
        transliteration: 'Al-ḥamdu lillāhi rabbil-‘ālamīn',
        translation: 'All praise is for Allah—Lord of all worlds.',
      },
      {
        number: 3,
        arabic: 'الرَّحْمَٰنِ الرَّحِيمِ',
        transliteration: 'Ar-Raḥmānir-Raḥīm',
        translation: 'The Most Compassionate, Most Merciful.',
      },
      {
        number: 4,
        arabic: 'مَالِكِ يَوْمِ الدِّينِ',
        transliteration: 'Māliki yaumid-dīn',
        translation: 'Master of the Day of Judgment.',
      },
      {
        number: 5,
        arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        transliteration: 'Iyyāka na‘budu wa iyyāka nasta‘īn',
        translation: 'You alone we worship and You alone we ask for help.',
      },
      {
        number: 6,
        arabic: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
        transliteration: 'Ihdinaṣ-ṣirāṭal-mustaqīm',
        translation: 'Guide us along the Straight Path.',
      },
      {
        number: 7,
        arabic: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
        transliteration: 'Ṣirāṭal-laḏīna an‘amta ‘alaihim ghairil-maghḍūbi ‘alaihim walāḍ-ḍāllīn',
        translation: 'The path of those You have blessed—not those You are displeased with, or those who are astray.',
      },
    ],
  },
  {
    number: 2,
    name: 'Al-Baqarah',
    arabicName: 'البقرة',
    revelationPlace: 'Medinan',
    versesCount: 286,
    meaning: 'The Cow',
    description: 'The longest surah of the Quran, covering law, faith, and stories of earlier prophets.',
  },
  {
    number: 3,
    name: "Ali 'Imran",
    arabicName: 'آل عمران',
    revelationPlace: 'Medinan',
    versesCount: 200,
    meaning: 'Family of Imran',
    description: 'Highlights lessons from the family of Imran and emphasizes steadfastness in faith.',
  },
  {
    number: 4,
    name: 'An-Nisa',
    arabicName: 'النساء',
    revelationPlace: 'Medinan',
    versesCount: 176,
    meaning: 'The Women',
    description: 'Focuses on social justice, inheritance, and principles that protect family and society.',
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    arabicName: 'المائدة',
    revelationPlace: 'Medinan',
    versesCount: 120,
    meaning: 'The Table Spread',
    description: 'Discusses covenants, dietary rules, and moral conduct for the believing community.',
  },
  {
    number: 6,
    name: "Al-An'am",
    arabicName: 'الأنعام',
    revelationPlace: 'Meccan',
    versesCount: 165,
    meaning: 'The Cattle',
    description: 'Affirms the oneness of Allah and refutes polytheistic practices.',
  },
  {
    number: 7,
    name: "Al-A'raf",
    arabicName: 'الأعراف',
    revelationPlace: 'Meccan',
    versesCount: 206,
    meaning: 'The Heights',
    description: 'Shares stories of previous prophets and the lessons drawn from their nations.',
  },
  {
    number: 8,
    name: 'Al-Anfal',
    arabicName: 'الأنفال',
    revelationPlace: 'Medinan',
    versesCount: 75,
    meaning: 'The Spoils of War',
    description: 'Addresses battlefield ethics and the spiritual dimension of struggle.',
  },
  {
    number: 9,
    name: 'At-Tawbah',
    arabicName: 'التوبة',
    revelationPlace: 'Medinan',
    versesCount: 129,
    meaning: 'Repentance',
    description: 'Calls for sincere repentance and exposes hypocrisy while outlining treaties and conduct.',
  },
  {
    number: 10,
    name: 'Yunus',
    arabicName: 'يونس',
    revelationPlace: 'Meccan',
    versesCount: 109,
    meaning: 'Jonah',
    description: 'Reassures believers through prophetic narratives emphasizing patience and trust in God.',
  },
  {
    number: 11,
    name: 'Hud',
    arabicName: 'هود',
    revelationPlace: 'Meccan',
    versesCount: 123,
    meaning: 'Hud',
    description: 'Highlights perseverance by recounting the struggles of Prophet Hud and other messengers.',
  },
  {
    number: 12,
    name: 'Yusuf',
    arabicName: 'يوسف',
    revelationPlace: 'Meccan',
    versesCount: 111,
    meaning: 'Joseph',
    description: 'Narrates the story of Prophet Joseph as a lesson in patience, forgiveness, and reliance on Allah.',
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    arabicName: 'الرعد',
    revelationPlace: 'Medinan',
    versesCount: 43,
    meaning: 'The Thunder',
    description: 'Reminds humanity of the power of Allah that is evident throughout creation.',
  },
  {
    number: 14,
    name: 'Ibrahim',
    arabicName: 'ابراهيم',
    revelationPlace: 'Meccan',
    versesCount: 52,
    meaning: 'Abraham',
    description: 'Reflects on the mission of Prophet Abraham and the gratitude due for divine guidance.',
  },
  {
    number: 15,
    name: 'Al-Hijr',
    arabicName: 'الحجر',
    revelationPlace: 'Meccan',
    versesCount: 99,
    meaning: 'The Rocky Tract',
    description: 'Warns of the consequences faced by past nations who denied their prophets.',
  },
  {
    number: 16,
    name: 'An-Nahl',
    arabicName: 'النحل',
    revelationPlace: 'Meccan',
    versesCount: 128,
    meaning: 'The Bee',
    description: 'Encourages gratitude by listing countless blessings bestowed upon humankind.',
  },
  {
    number: 17,
    name: 'Al-Isra',
    arabicName: 'الإسراء',
    revelationPlace: 'Meccan',
    versesCount: 111,
    meaning: 'The Night Journey',
    description: 'Opens with the miraculous journey of the Prophet ﷺ and imparts ethical guidelines.',
  },
  {
    number: 18,
    name: 'Al-Kahf',
    arabicName: 'الكهف',
    revelationPlace: 'Meccan',
    versesCount: 110,
    meaning: 'The Cave',
    description: 'Relates parables that teach reliance on Allah and patience under trial.',
  },
  {
    number: 19,
    name: 'Maryam',
    arabicName: 'مريم',
    revelationPlace: 'Meccan',
    versesCount: 98,
    meaning: 'Mary',
    description: 'Centers on Mary and other devout individuals, highlighting miraculous births and faith.',
  },
  {
    number: 20,
    name: 'Ta-Ha',
    arabicName: 'طه',
    revelationPlace: 'Meccan',
    versesCount: 135,
    meaning: 'Ta-Ha',
    description: 'Comforts the Prophet ﷺ and recounts the mission of Prophet Moses.',
  },
  {
    number: 21,
    name: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    revelationPlace: 'Meccan',
    versesCount: 112,
    meaning: 'The Prophets',
    description: 'Summarizes the lives of multiple prophets to reinforce steadfastness.',
  },
  {
    number: 22,
    name: 'Al-Hajj',
    arabicName: 'الحج',
    revelationPlace: 'Medinan',
    versesCount: 78,
    meaning: 'The Pilgrimage',
    description: 'Combines Meccan and Medinan passages to explain the rites and spiritual purpose of Hajj.',
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    arabicName: 'المؤمنون',
    revelationPlace: 'Meccan',
    versesCount: 118,
    meaning: 'The Believers',
    description: 'Highlights characteristics of successful believers and lessons from earlier prophets.',
  },
  {
    number: 24,
    name: 'An-Nur',
    arabicName: 'النور',
    revelationPlace: 'Medinan',
    versesCount: 64,
    meaning: 'The Light',
    description: 'Establishes social etiquette, modesty, and the importance of personal responsibility.',
  },
  {
    number: 25,
    name: 'Al-Furqan',
    arabicName: 'الفرقان',
    revelationPlace: 'Meccan',
    versesCount: 77,
    meaning: 'The Criterion',
    description: 'Differentiates between truth and falsehood and portrays the qualities of true servants of Allah.',
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    arabicName: 'الشعراء',
    revelationPlace: 'Meccan',
    versesCount: 227,
    meaning: 'The Poets',
    description: 'Recounts several prophetic stories, emphasizing that guidance belongs to Allah.',
  },
  {
    number: 27,
    name: 'An-Naml',
    arabicName: 'النمل',
    revelationPlace: 'Meccan',
    versesCount: 93,
    meaning: 'The Ant',
    description: 'Shares the wisdom of Prophet Solomon and other prophets, stressing gratitude.',
  },
  {
    number: 28,
    name: 'Al-Qasas',
    arabicName: 'القصص',
    revelationPlace: 'Meccan',
    versesCount: 88,
    meaning: 'The Stories',
    description: 'Focuses on the life of Prophet Moses and the consequences of arrogance.',
  },
  {
    number: 29,
    name: "Al-'Ankabut",
    arabicName: 'العنكبوت',
    revelationPlace: 'Meccan',
    versesCount: 69,
    meaning: 'The Spider',
    description: 'Compares weak reliance on false gods to a fragile spider’s web.',
  },
  {
    number: 30,
    name: "Ar-Rum",
    arabicName: 'الروم',
    revelationPlace: 'Meccan',
    versesCount: 60,
    meaning: 'The Romans',
    description: 'Predicts the Byzantine victory and reflects on signs of Allah in nature and history.',
  },
  {
    number: 31,
    name: 'Luqman',
    arabicName: 'لقمان',
    revelationPlace: 'Meccan',
    versesCount: 34,
    meaning: 'Luqman',
    description: 'Highlights the wise counsel of Luqman to his son on faith and conduct.',
  },
  {
    number: 32,
    name: 'As-Sajdah',
    arabicName: 'السجدة',
    revelationPlace: 'Meccan',
    versesCount: 30,
    meaning: 'The Prostration',
    description: 'Encourages humility and reflection on the creation of humanity.',
  },
  {
    number: 33,
    name: 'Al-Ahzab',
    arabicName: 'الأحزاب',
    revelationPlace: 'Medinan',
    versesCount: 73,
    meaning: 'The Confederates',
    description: 'Discusses the siege of Medina and outlines etiquette for the Prophet’s household.',
  },
  {
    number: 34,
    name: 'Saba',
    arabicName: 'سبأ',
    revelationPlace: 'Meccan',
    versesCount: 54,
    meaning: 'Sheba',
    description: 'Recounts the story of the people of Sheba and the need for gratitude.',
  },
  {
    number: 35,
    name: 'Fatir',
    arabicName: 'فاطر',
    revelationPlace: 'Meccan',
    versesCount: 45,
    meaning: 'Originator',
    description: 'Celebrates Allah as the Creator and warns those who deny His favors.',
  },
  {
    number: 36,
    name: 'Ya-Sin',
    arabicName: 'يس',
    revelationPlace: 'Meccan',
    versesCount: 83,
    meaning: 'Ya-Sin',
    description: 'Known as the heart of the Quran, it underscores the urgency of the prophetic message.',
  },
  {
    number: 37,
    name: 'As-Saffat',
    arabicName: 'الصافات',
    revelationPlace: 'Meccan',
    versesCount: 182,
    meaning: 'Those Who Stand in Rows',
    description: 'Depicts ranks of angels and recounts stories of obedience among prophets.',
  },
  {
    number: 38,
    name: 'Sad',
    arabicName: 'ص',
    revelationPlace: 'Meccan',
    versesCount: 88,
    meaning: 'Sad',
    description: 'Addresses the rejection faced by prophets and affirms divine justice.',
  },
  {
    number: 39,
    name: 'Az-Zumar',
    arabicName: 'الزمر',
    revelationPlace: 'Meccan',
    versesCount: 75,
    meaning: 'The Groups',
    description: 'Encourages sincere worship and depicts the final gathering on the Day of Judgment.',
  },
  {
    number: 40,
    name: 'Ghafir',
    arabicName: 'غافر',
    revelationPlace: 'Meccan',
    versesCount: 85,
    meaning: 'The Forgiver',
    description: 'Reassures the believers that Allah forgives, while warning those who plot evil.',
  },
  {
    number: 41,
    name: 'Fussilat',
    arabicName: 'فصلت',
    revelationPlace: 'Meccan',
    versesCount: 54,
    meaning: 'Explained in Detail',
    description: 'The Quran is described as a book whose verses are clearly detailed.',
  },
  {
    number: 42,
    name: 'Ash-Shura',
    arabicName: 'الشورى',
    revelationPlace: 'Meccan',
    versesCount: 53,
    meaning: 'Consultation',
    description: 'Advocates mutual consultation and unity within the believing community.',
  },
  {
    number: 43,
    name: 'Az-Zukhruf',
    arabicName: 'الزخرف',
    revelationPlace: 'Meccan',
    versesCount: 89,
    meaning: 'The Ornaments of Gold',
    description: 'Warns against being dazzled by worldly luxury at the expense of faith.',
  },
  {
    number: 44,
    name: 'Ad-Dukhan',
    arabicName: 'الدخان',
    revelationPlace: 'Meccan',
    versesCount: 59,
    meaning: 'The Smoke',
    description: 'Portrays scenes of the Hereafter while reminding people of past warnings.',
  },
  {
    number: 45,
    name: 'Al-Jathiyah',
    arabicName: 'الجاثية',
    revelationPlace: 'Meccan',
    versesCount: 37,
    meaning: 'The Crouching',
    description: 'Depicts nations kneeling on Judgment Day awaiting their record of deeds.',
  },
  {
    number: 46,
    name: 'Al-Ahqaf',
    arabicName: 'الأحقاف',
    revelationPlace: 'Meccan',
    versesCount: 35,
    meaning: 'The Dunes',
    description: 'Mentions the people of ‘Ad and stresses gratitude for prophetic guidance.',
  },
  {
    number: 47,
    name: 'Muhammad',
    arabicName: 'محمد',
    revelationPlace: 'Medinan',
    versesCount: 38,
    meaning: 'Muhammad',
    description: 'Encourages loyalty to the Prophet ﷺ and contrasts believers with hypocrites.',
  },
  {
    number: 48,
    name: 'Al-Fath',
    arabicName: 'الفتح',
    revelationPlace: 'Medinan',
    versesCount: 29,
    meaning: 'The Victory',
    description: 'Celebrates the Treaty of Hudaybiyyah as a manifest victory.',
  },
  {
    number: 49,
    name: 'Al-Hujurat',
    arabicName: 'الحجرات',
    revelationPlace: 'Medinan',
    versesCount: 18,
    meaning: 'The Chambers',
    description: 'Teaches etiquette, brotherhood, and the danger of baseless suspicion.',
  },
  {
    number: 50,
    name: 'Qaf',
    arabicName: 'ق',
    revelationPlace: 'Meccan',
    versesCount: 45,
    meaning: 'Qaf',
    description: 'Powerfully describes resurrection and the closeness of Allah’s knowledge.',
  },
  {
    number: 51,
    name: "Adh-Dhariyat",
    arabicName: 'الذاريات',
    revelationPlace: 'Meccan',
    versesCount: 60,
    meaning: 'The Winnowing Winds',
    description: 'Swears by natural phenomena to emphasize the reality of recompense.',
  },
  {
    number: 52,
    name: 'At-Tur',
    arabicName: 'الطور',
    revelationPlace: 'Meccan',
    versesCount: 49,
    meaning: 'The Mount',
    description: 'Reaffirms the certainty of the Last Day with striking imagery.',
  },
  {
    number: 53,
    name: 'An-Najm',
    arabicName: 'النجم',
    revelationPlace: 'Meccan',
    versesCount: 62,
    meaning: 'The Star',
    description: 'Confirms the validity of the Prophet’s revelations and condemns idolatry.',
  },
  {
    number: 54,
    name: 'Al-Qamar',
    arabicName: 'القمر',
    revelationPlace: 'Meccan',
    versesCount: 55,
    meaning: 'The Moon',
    description: 'Warns rejecters by recounting the fate of earlier peoples.',
  },
  {
    number: 55,
    name: 'Ar-Rahman',
    arabicName: 'الرحمن',
    revelationPlace: 'Medinan',
    versesCount: 78,
    meaning: 'The Most Merciful',
    description: 'Repeatedly asks, “Which favors of your Lord will you deny?” to awaken gratitude.',
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    arabicName: 'الواقعة',
    revelationPlace: 'Meccan',
    versesCount: 96,
    meaning: 'The Inevitable',
    description: 'Describes scenes of the Resurrection and the result for each group of people.',
  },
  {
    number: 57,
    name: 'Al-Hadid',
    arabicName: 'الحديد',
    revelationPlace: 'Medinan',
    versesCount: 29,
    meaning: 'The Iron',
    description: 'Encourages charity and determination like iron in the path of Allah.',
  },
  {
    number: 58,
    name: 'Al-Mujadila',
    arabicName: 'المجادلة',
    revelationPlace: 'Medinan',
    versesCount: 22,
    meaning: 'The Pleading Woman',
    description: 'Addresses social justice by honoring the plea of a woman before the Prophet ﷺ.',
  },
  {
    number: 59,
    name: 'Al-Hashr',
    arabicName: 'الحشر',
    revelationPlace: 'Medinan',
    versesCount: 24,
    meaning: 'The Exile',
    description: 'Refers to the expulsion of hostile tribes and includes exalted Names of Allah.',
  },
  {
    number: 60,
    name: 'Al-Mumtahanah',
    arabicName: 'الممتحنة',
    revelationPlace: 'Medinan',
    versesCount: 13,
    meaning: 'The Woman to be Examined',
    description: 'Gives guidelines for interactions with non-Muslims and loyalty to believers.',
  },
  {
    number: 61,
    name: 'As-Saff',
    arabicName: 'الصف',
    revelationPlace: 'Medinan',
    versesCount: 14,
    meaning: 'The Ranks',
    description: 'Urges believers to stand shoulder to shoulder in Allah’s cause.',
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    arabicName: 'الجمعة',
    revelationPlace: 'Medinan',
    versesCount: 11,
    meaning: 'The Friday Congregation',
    description: 'Highlights the merit of Friday prayer and listening attentively to the khutbah.',
  },
  {
    number: 63,
    name: 'Al-Munafiqun',
    arabicName: 'المنافقون',
    revelationPlace: 'Medinan',
    versesCount: 11,
    meaning: 'The Hypocrites',
    description: 'Exposes the traits of hypocrisy so believers remain vigilant.',
  },
  {
    number: 64,
    name: 'At-Taghabun',
    arabicName: 'التغابن',
    revelationPlace: 'Medinan',
    versesCount: 18,
    meaning: 'Mutual Loss and Gain',
    description: 'Reminds humanity that worldly trade is temporary while the Hereafter is lasting.',
  },
  {
    number: 65,
    name: 'At-Talaq',
    arabicName: 'الطلاق',
    revelationPlace: 'Medinan',
    versesCount: 12,
    meaning: 'The Divorce',
    description: 'Outlines compassionate rules governing divorce and waiting periods.',
  },
  {
    number: 66,
    name: 'At-Tahrim',
    arabicName: 'التحريم',
    revelationPlace: 'Medinan',
    versesCount: 12,
    meaning: 'The Prohibition',
    description: 'Advises the Prophet’s household and believers to prioritize Allah above all.',
  },
  {
    number: 67,
    name: 'Al-Mulk',
    arabicName: 'الملك',
    revelationPlace: 'Meccan',
    versesCount: 30,
    meaning: 'The Sovereignty',
    description: 'Encourages reflection on the heavens as a sign of Allah’s absolute control.',
  },
  {
    number: 68,
    name: 'Al-Qalam',
    arabicName: 'القلم',
    revelationPlace: 'Meccan',
    versesCount: 52,
    meaning: 'The Pen',
    description: 'Defends the Prophet’s character and warns against greed through parables.',
  },
  {
    number: 69,
    name: 'Al-Haqqah',
    arabicName: 'الحاقة',
    revelationPlace: 'Meccan',
    versesCount: 52,
    meaning: 'The Inevitable Reality',
    description: 'Vividly portrays the Day of Judgment and the contrast between believers and deniers.',
  },
  {
    number: 70,
    name: "Al-Ma'arij",
    arabicName: 'المعارج',
    revelationPlace: 'Meccan',
    versesCount: 44,
    meaning: 'The Ascending Stairways',
    description: 'Describes the ascent of angels and calls for patience amid trials.',
  },
  {
    number: 71,
    name: 'Nuh',
    arabicName: 'نوح',
    revelationPlace: 'Meccan',
    versesCount: 28,
    meaning: 'Noah',
    description: 'Narrates Prophet Noah’s persistent invitation to his people.',
  },
  {
    number: 72,
    name: 'Al-Jinn',
    arabicName: 'الجن',
    revelationPlace: 'Meccan',
    versesCount: 28,
    meaning: 'The Jinn',
    description: 'Recounts how a group of jinn listened to the Quran and embraced its message.',
  },
  {
    number: 73,
    name: 'Al-Muzzammil',
    arabicName: 'المزمل',
    revelationPlace: 'Meccan',
    versesCount: 20,
    meaning: 'The Enshrouded One',
    description: 'Encourages devotion during the night and perseverance during the day.',
  },
  {
    number: 74,
    name: 'Al-Muddathir',
    arabicName: 'المدثر',
    revelationPlace: 'Meccan',
    versesCount: 56,
    meaning: 'The Cloaked One',
    description: 'Commands the Prophet ﷺ to arise and warn, while describing the horrors of Hell.',
  },
  {
    number: 75,
    name: 'Al-Qiyamah',
    arabicName: 'القيامة',
    revelationPlace: 'Meccan',
    versesCount: 40,
    meaning: 'The Resurrection',
    description: 'Assures the certainty of resurrection and the accountability that follows.',
  },
  {
    number: 76,
    name: "Al-Insan",
    arabicName: 'الانسان',
    revelationPlace: 'Medinan',
    versesCount: 31,
    meaning: 'Human',
    description: 'Speaks about gratitude, charity, and the eternal reward for the righteous.',
  },
  {
    number: 77,
    name: 'Al-Mursalat',
    arabicName: 'المرسلات',
    revelationPlace: 'Meccan',
    versesCount: 50,
    meaning: 'Those Sent Forth',
    description: 'Warns the deniers through oaths over the unstoppable winds and messengers.',
  },
  {
    number: 78,
    name: 'An-Naba',
    arabicName: 'النبأ',
    revelationPlace: 'Meccan',
    versesCount: 40,
    meaning: 'The Great News',
    description: 'Asks rhetorical questions about the great news of resurrection and recompense.',
  },
  {
    number: 79,
    name: "An-Nazi'at",
    arabicName: 'النازعات',
    revelationPlace: 'Meccan',
    versesCount: 46,
    meaning: 'Those Who Drag Forth',
    description: 'References powerful angels and their role in bringing souls to account.',
  },
  {
    number: 80,
    name: 'Abasa',
    arabicName: 'عبس',
    revelationPlace: 'Meccan',
    versesCount: 42,
    meaning: 'He Frowned',
    description: 'Teaches the Prophet ﷺ and all believers about caring for sincere seekers.',
  },
  {
    number: 81,
    name: 'At-Takwir',
    arabicName: 'التكوير',
    revelationPlace: 'Meccan',
    versesCount: 29,
    meaning: 'The Overthrowing',
    description: 'Depicts cosmic events that will occur in the final Hour.',
  },
  {
    number: 82,
    name: 'Al-Infitar',
    arabicName: 'الإنفطار',
    revelationPlace: 'Meccan',
    versesCount: 19,
    meaning: 'The Cleaving Asunder',
    description: 'Reminds people to honor their Lord who created and proportioned them.',
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    arabicName: 'المطففين',
    revelationPlace: 'Meccan',
    versesCount: 36,
    meaning: 'The Defrauders',
    description: 'Condemns those who cheat in trade and contrasts their fate with the righteous.',
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    arabicName: 'الإنشقاق',
    revelationPlace: 'Meccan',
    versesCount: 25,
    meaning: 'The Splitting Asunder',
    description: 'Presents the inevitable meeting with Allah and the distribution of records.',
  },
  {
    number: 85,
    name: 'Al-Buruj',
    arabicName: 'البروج',
    revelationPlace: 'Meccan',
    versesCount: 22,
    meaning: 'The Constellations',
    description: 'Mentions persecuted believers and comforts them with the promise of Paradise.',
  },
  {
    number: 86,
    name: 'At-Tariq',
    arabicName: 'الطارق',
    revelationPlace: 'Meccan',
    versesCount: 17,
    meaning: 'The Nightcomer',
    description: 'Swears by heavenly bodies to remind humanity of their humble origins.',
  },
  {
    number: 87,
    name: "Al-A'la",
    arabicName: 'الأعلى',
    revelationPlace: 'Meccan',
    versesCount: 19,
    meaning: 'The Most High',
    description: 'Encourages glorifying the Most High and prioritizing the everlasting life.',
  },
  {
    number: 88,
    name: 'Al-Ghashiyah',
    arabicName: 'الغاشية',
    revelationPlace: 'Meccan',
    versesCount: 26,
    meaning: 'The Overwhelming Event',
    description: 'Paints contrasting images of the people of Paradise and Hellfire.',
  },
  {
    number: 89,
    name: 'Al-Fajr',
    arabicName: 'الفجر',
    revelationPlace: 'Meccan',
    versesCount: 30,
    meaning: 'The Dawn',
    description: 'Warns those who oppress and reassures the tranquil soul at the end of life.',
  },
  {
    number: 90,
    name: 'Al-Balad',
    arabicName: 'البلد',
    revelationPlace: 'Meccan',
    versesCount: 20,
    meaning: 'The City',
    description: 'Discusses the sacred city of Makkah and the uphill struggle for righteousness.',
  },
  {
    number: 91,
    name: 'Ash-Shams',
    arabicName: 'الشمس',
    revelationPlace: 'Meccan',
    versesCount: 15,
    meaning: 'The Sun',
    description: 'Stresses the need to purify the soul just as Allah swears by His creation.',
  },
  {
    number: 92,
    name: 'Al-Layl',
    arabicName: 'الليل',
    revelationPlace: 'Meccan',
    versesCount: 21,
    meaning: 'The Night',
    description: 'Contrasts the fates of the generous believer and the stingy miser.',
  },
  {
    number: 93,
    name: 'Ad-Duha',
    arabicName: 'الضحى',
    revelationPlace: 'Meccan',
    versesCount: 11,
    meaning: 'The Morning Sunlight',
    description: 'Consoles the Prophet ﷺ and reminds him of Allah’s continual care.',
  },
  {
    number: 94,
    name: 'Ash-Sharh',
    arabicName: 'الشرح',
    revelationPlace: 'Meccan',
    versesCount: 8,
    meaning: 'The Relief',
    description: 'Promises relief after hardship and directs believers to their Lord.',
  },
  {
    number: 95,
    name: 'At-Tin',
    arabicName: 'التين',
    revelationPlace: 'Meccan',
    versesCount: 8,
    meaning: 'The Fig',
    description: 'Reflects on the nobility of human creation and the accountability that follows.',
  },
  {
    number: 96,
    name: 'Al-Alaq',
    arabicName: 'العلق',
    revelationPlace: 'Meccan',
    versesCount: 19,
    meaning: 'The Clinging Clot',
    description: 'Contains the first verses revealed, commanding the act of reading in Allah’s name.',
  },
  {
    number: 97,
    name: 'Al-Qadr',
    arabicName: 'القدر',
    revelationPlace: 'Meccan',
    versesCount: 5,
    meaning: 'The Night of Decree',
    description: 'Describes the blessed night when the Quran was revealed.',
  },
  {
    number: 98,
    name: 'Al-Bayyinah',
    arabicName: 'البينة',
    revelationPlace: 'Medinan',
    versesCount: 8,
    meaning: 'The Clear Proof',
    description: 'Distinguishes the people of the scripture who believed from those who rejected.',
  },
  {
    number: 99,
    name: 'Az-Zalzalah',
    arabicName: 'الزلزلة',
    revelationPlace: 'Medinan',
    versesCount: 8,
    meaning: 'The Earthquake',
    description: 'Depicts the final earthquake when earth expels its burdens.',
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    arabicName: 'العاديات',
    revelationPlace: 'Meccan',
    versesCount: 11,
    meaning: 'The Courser',
    description: 'Swears by galloping horses to expose human ingratitude.',
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    arabicName: 'القارعة',
    revelationPlace: 'Meccan',
    versesCount: 11,
    meaning: 'The Striking Calamity',
    description: 'Questions humanity about the overwhelming event and the balancing of deeds.',
  },
  {
    number: 102,
    name: 'At-Takathur',
    arabicName: 'التكاثر',
    revelationPlace: 'Meccan',
    versesCount: 8,
    meaning: 'The Rivalry in Worldly Increase',
    description: 'Warns that obsession with rivalry distracts from remembering the Hereafter.',
  },
  {
    number: 103,
    name: 'Al-Asr',
    arabicName: 'العصر',
    revelationPlace: 'Meccan',
    versesCount: 3,
    meaning: 'The Declining Day',
    description: 'Summarizes salvation in faith, good deeds, truth, and patience.',
  },
  {
    number: 104,
    name: 'Al-Humazah',
    arabicName: 'الهمزة',
    revelationPlace: 'Meccan',
    versesCount: 9,
    meaning: 'The Backbiter',
    description: 'Condemns slanderers consumed by hoarding wealth.',
  },
  {
    number: 105,
    name: 'Al-Fil',
    arabicName: 'الفيل',
    revelationPlace: 'Meccan',
    versesCount: 5,
    meaning: 'The Elephant',
    description: 'Reminds of the Year of the Elephant when Allah protected the Kaabah.',
  },
  {
    number: 106,
    name: 'Quraysh',
    arabicName: 'قريش',
    revelationPlace: 'Meccan',
    versesCount: 4,
    meaning: 'The Quraysh',
    description: 'Calls Quraysh to worship the Lord of the Kaabah who feeds and protects them.',
  },
  {
    number: 107,
    name: "Al-Ma'un",
    arabicName: 'الماعون',
    revelationPlace: 'Meccan',
    versesCount: 7,
    meaning: 'The Small Kindness',
    description: 'Denounces hypocrisy and neglecting acts of kindness.',
  },
  {
    number: 108,
    name: 'Al-Kawthar',
    arabicName: 'الكوثر',
    revelationPlace: 'Meccan',
    versesCount: 3,
    meaning: 'The Abundance',
    description: 'A short surah granting the Prophet ﷺ a river in Paradise and urging gratitude.',
  },
  {
    number: 109,
    name: 'Al-Kafirun',
    arabicName: 'الكافرون',
    revelationPlace: 'Meccan',
    versesCount: 6,
    meaning: 'The Disbelievers',
    description: 'Declares a respectful separation between the beliefs of Muslims and idolaters.',
  },
  {
    number: 110,
    name: 'An-Nasr',
    arabicName: 'النصر',
    revelationPlace: 'Medinan',
    versesCount: 3,
    meaning: 'The Help',
    description: 'Foretells the victory of Islam and instructs gratitude and repentance.',
  },
  {
    number: 111,
    name: 'Al-Masad',
    arabicName: 'المسد',
    revelationPlace: 'Meccan',
    versesCount: 5,
    meaning: 'The Palm Fiber',
    description: 'Condemns Abu Lahab and his wife for their hostility to Islam.',
  },
  {
    number: 112,
    name: 'Al-Ikhlas',
    arabicName: 'الإخلاص',
    revelationPlace: 'Meccan',
    versesCount: 4,
    meaning: 'Sincerity',
    description: 'A concise declaration of the oneness of Allah.',
    verses: [
      {
        number: 1,
        arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ',
        transliteration: 'Qul huwa Allāhu aḥad',
        translation: 'Say, “He is Allah—One and Indivisible.”',
      },
      {
        number: 2,
        arabic: 'اللَّهُ الصَّمَدُ',
        transliteration: 'Allāhuṣ-ṣamad',
        translation: 'Allah—the Sustainer (needed by all).',
      },
      {
        number: 3,
        arabic: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
        transliteration: 'Lam yalid walam yūlad',
        translation: 'He has never had offspring, nor was He born.',
      },
      {
        number: 4,
        arabic: 'وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
        transliteration: 'Walam yakun lahu kufuwan aḥad',
        translation: 'And there is none comparable to Him.',
      },
    ],
  },
  {
    number: 113,
    name: 'Al-Falaq',
    arabicName: 'الفلق',
    revelationPlace: 'Meccan',
    versesCount: 5,
    meaning: 'Daybreak',
    description: 'A prayer seeking protection from every harm.',
    verses: [
      {
        number: 1,
        arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ',
        transliteration: 'Qul a‘ūdhu birabbil-falaq',
        translation: 'Say, “I seek refuge in the Lord of daybreak.”',
      },
      {
        number: 2,
        arabic: 'مِن شَرِّ مَا خَلَقَ',
        transliteration: 'Min sharri mā khalaq',
        translation: 'From the evil of whatever He has created.',
      },
      {
        number: 3,
        arabic: 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ',
        transliteration: 'Wa min sharri ghāsiqin iḏā waqab',
        translation: 'And from the evil of the night when it grows dark.',
      },
      {
        number: 4,
        arabic: 'وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ',
        transliteration: 'Wa min sharri an-naffāthāti fil-‘uqad',
        translation: 'And from the evil of those who practice witchcraft.',
      },
      {
        number: 5,
        arabic: 'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
        transliteration: 'Wa min sharri ḥāsidin iḏā ḥasad',
        translation: 'And from the evil of an envier when they envy.',
      },
    ],
  },
  {
    number: 114,
    name: 'An-Nas',
    arabicName: 'الناس',
    revelationPlace: 'Meccan',
    versesCount: 6,
    meaning: 'Mankind',
    description: 'A supplication seeking refuge in Allah from whispered temptations.',
    verses: [
      {
        number: 1,
        arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
        transliteration: 'Qul a‘ūdhu birabbin-nās',
        translation: 'Say, “I seek refuge in the Lord of humankind.”',
      },
      {
        number: 2,
        arabic: 'مَلِكِ النَّاسِ',
        transliteration: 'Malikin-nās',
        translation: 'The Master of humankind.',
      },
      {
        number: 3,
        arabic: 'إِلَٰهِ النَّاسِ',
        transliteration: 'Ilāhin-nās',
        translation: 'The God of humankind.',
      },
      {
        number: 4,
        arabic: 'مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ',
        transliteration: 'Min sharri al-waswās al-khannās',
        translation: 'From the evil of the lurking whisperer.',
      },
      {
        number: 5,
        arabic: 'الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ',
        transliteration: 'Alladhī yuwaswisu fī ṣudūrin-nās',
        translation: 'Who whispers into the hearts of humankind.',
      },
      {
        number: 6,
        arabic: 'مِنَ الْجِنَّةِ وَالنَّاسِ',
        transliteration: 'Minal-jinnati wan-nās',
        translation: 'From among jinn and humankind.',
      },
    ],
  },
];
